---
title: "Transform raster to point shapefile"
author: "Jean-Philippe Gilbert"
date: "22/06/2021"
output: html_document
---

```{r eval = FALSE}
library(raster)
library(rgdal)
```

Code simple qui prends les raster et les transforms en point (utilisé pour remplir les trous dans pour les images de chaleur mais finalement j'utilise pas ces images, n'apporte pas de différence)

Test le prototype
```{r eval = FALSE}
image <- raster("C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2015\\Image_raw\\LC80150282015261LGN01_LST.tif")
point <- rasterToPoints(image, spatial = TRUE)
rgdal::writeOGR(obj=point, dsn ='C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2016\\shp', layer =  'point_LC80150282015261LGN01_LST',
                driver = "ESRI Shapefile")
```


Puis applique à tous les images du fichier (ne pas oublier de changer l'année du fichier)
```{r eval=FALSE}
folder <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2019\\Image_raw\\')
folder_full <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2019\\Image_raw\\',full.names = TRUE)
folder_shp <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2019\\shp\\')
for(i in 1:length(folder))
{
  nom <- stringr::str_remove(folder[i], ".tif")
  nom <- paste("point_", nom, sep = "")
  nom <- paste(nom, ".shp", sep="")
  if(nom %in% folder_shp)
  {
    next
  }else
  {
    print(i)
    nom2 <- stringr::str_remove(folder[i], ".tif")
    nom2 <- paste("point_", nom2, sep = "")
    image <- raster(folder_full[i])
    point <- rasterToPoints(image, spatial = TRUE)
    rgdal::writeOGR(obj=point, dsn ='C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2019\\shp', layer =  nom2,
                    driver = "ESRI Shapefile")
  }
}

folder <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2020\\Image_raw\\')
folder_full <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2020\\Image_raw\\',full.names = TRUE)
folder_shp <- list.files('C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2020\\shp\\')
for(i in 1:length(folder))
{
  nom <- stringr::str_remove(folder[i], ".tif")
  nom <- paste("point_", nom, sep = "")
  nom <- paste(nom, ".shp", sep="")
  if(nom %in% folder_shp)
  {
    next
  }else
  {
    print(i)
    nom2 <- stringr::str_remove(folder[i], ".tif")
    nom2 <- paste("point_", nom2, sep = "")
    image <- raster(folder_full[i])
    point <- rasterToPoints(image, spatial = TRUE)
    rgdal::writeOGR(obj=point, dsn ='C:\\Users\\JPGIL11\\Desktop\\Image_wang\\Image_2020\\shp', layer =  nom2,
                    driver = "ESRI Shapefile")
  }
}

```
